### PR TITLE
Add packaging to setup.py dependencies

### LINKED ISSUE #45: Missing install_requires on packaging
Since the code now requires packaging, `setup.py` should indicate the dependency as well.

### PR DESCRIPTION
**Pull request by VladimirSlavik**
Closes #45

### CODE REVIEW

**Review by poncovka — APPROVED** [review]

**Review by vojtechtrefny — APPROVED** [review]

**Review by jkonecny12 — APPROVED** [review]
Looks great to me. Thanks!

**Comment by jkonecny12** [comment]
The pylint error doesn't look related.

**Comment by jkonecny12** [comment]
Merging to solve current test failures on other projects. The pylint issues could be resolved later.

**Comment by bcl** [comment]
That pylint explosion is because that version hasn't been updated to work with the latest python 3 -- I think adamw built a new version with the fix for Fedora the other day, so next time it should be ok.

**Pull request merged**
