### PR TITLE
Use pylint from python which starts pocketlint

### PR DESCRIPTION
**Pull request by jkonecny12**
Remove the find pylint binary code and use "python -m pylint" with python used to start pocketlint.

This will make the code a lot easier and most of all it will enable to use pylint installed by pip.

### CODE REVIEW

**Review by bcl — APPROVED** [review]
Looks ok to me

**Comment by jkonecny12** [comment]
**DO NOT MERGE**
Unfortunately it looks like this is not working properly with the rpm package.

**Comment by jkonecny12** [comment]
There was a problem with dependencies when installing from pip. So these changes should work correctly after https://github.com/rhinstaller/pocketlint/pull/28 and https://github.com/rhinstaller/pocketlint/pull/27 will be merged.

**Comment by jkonecny12** [comment]
**REBASED**
This patch is ready for merge now.

**Review by vojtechtrefny — APPROVED** [review]
Looks good to me.

**Pull request merged**
