### PR TITLE
Make bumpver lang independent

### PR DESCRIPTION
**Pull request by jkonecny12**
The date command changes based on the language set on the system which results in invalid changelog. Set the date command to English only.

### CODE REVIEW

**Review by vpodzime — COMMENTED** [review]
I think you should use `LC_ALL=C.UTF-8`.

**Comment by jkonecny12** [comment]
I'm using this solution in simpleline but no problem to change it on both places :)

**Comment by jkonecny12** [comment]
**UPDATED**

**Review by vojtechtrefny — APPROVED** [review]
ACK

**Pull request merged**
