### PR TITLE
Use new astroid class names

### PR DESCRIPTION
**Pull request by hroncok**
Those are available with 1.6.x and 2.x as well, but the old one were removed from 2.x.

Fixes https://github.com/rhinstaller/pocketlint/issues/21

### CODE REVIEW

**Review by jkonecny12 — APPROVED** [review]
Looks good to me.

**Comment by jkonecny12** [comment]
Jenkins, it's ok to test.

**Comment by jkonecny12** [comment]
jenkins, test this please

**Comment by hroncok** [comment]
What's wrong? The CI is behind closed doors.

**Comment by jkonecny12** [comment]
The old Jenkins is broken and the new one has different structure. I'm trying to set it properly. Sorry for the spamming.

**Comment by jkonecny12** [comment]
jenkins, test this please

**Comment by jkonecny12** [comment]
Tests went good. You can ignore the first one.

@vojtechtrefny will merge this soon.

Thanks for the changes :) .

**Comment by vojtechtrefny** [comment]
Thank you for the fix.

**Comment by hroncok** [comment]
Thanks for merge. Please get this to Fedora rawhide within days.

**Pull request merged**
