### PR TITLE
Ignore config file line printed by pylint

### PR DESCRIPTION
**Pull request by vojtechtrefny**
Since 1.9 pylint started printing location of config file to
stderr and pocketlint thinks this is a pylint warning/error. This
behaviour was fixed in pylint 2.0.

### CODE REVIEW

**Review by jkonecny12 — CHANGES_REQUESTED** [review]
Please add comment with explanation why is this required.

**Comment by vojtechtrefny** [comment]
> Please add comment with explanation why is this required.

I think the original comment (*This is not an error message.  Ignore it.*) together with the commit message should be good enough for this too. It's not an error message just some debug message that is printed on some pylint versions. But if you think it is really necessary, I'll add some comment.

**Comment by jkonecny12** [comment]
I meant comment with info that this is required because of bug in pylint and link on the pylint issue.

**Review by jkonecny12 — APPROVED** [review]
This is not a blocking issue. It is more nice to have.

Thanks for this fix.

**Comment by vojtechtrefny** [comment]
I've added link to the pylint issue into the commit message.

**Comment by jkonecny12** [comment]
Thanks, this looks much better!

**Pull request merged**
